### ISSUE TITLE
Problem activating package

### ISSUE THREAD

**Issue by wiedzmin** [emacs-lsp/lsp-python#1]
I'm installing lsp-python using package.el, and right after installation there is no problem. But then, when after Emacs restart, autoloads come into play and the following backtrace pops up:

Debugger entered--Lisp error: (void-function lsp-define-stdio-client)
  (lsp-define-stdio-client (quote python-mode) "python" (quote stdio) (lsp-make-traverser (function (lambda (dir) (directory-files dir nil "\\(__init__\\|setup\\)\\.py")))) "Python Language Server" (quote ("pyls")))
  eval-buffer(#<buffer  *load*-518347> nil "/home/octocat/.emacs.d/elpa/lsp-python-20170421.322/lsp-python-autoloads.el" nil t)  ; Reading at buffer position 490
  load-with-code-conversion("/home/octocat/.emacs.d/elpa/lsp-python-20170421.322/lsp-python-autoloads.el" "/home/octocat/.emacs.d/elpa/lsp-python-20170421.322/lsp-python-autoloads.el" nil t)
  load("/home/octocat/.emacs.d/elpa/lsp-python-20170421.322/lsp-python-autoloads" nil t)
  package--activate-autoloads-and-load-path([cl-struct-package-desc lsp-python (20170421 322) "Python support for lsp-mode" ((lsp-mode (2 0))) nil nil "/home/octocat/.emacs.d/elpa/lsp-python-20170421.322" ((:keywords "python") (:url . "https://github.com/emacs-lsp/lsp-python")) nil])
  package--load-files-for-activation([cl-struct-package-desc lsp-python (20170421 322) "Python support for lsp-mode" ((lsp-mode (2 0))) nil nil "/home/octocat/.emacs.d/elpa/lsp-python-20170421.322" ((:keywords "python") (:url . "https://github.com/emacs-lsp/lsp-python")) nil] nil)
  package-activate-1([cl-struct-package-desc lsp-python (20170421 322) "Python support for lsp-mode" ((lsp-mode (2 0))) nil nil "/home/octocat/.emacs.d/elpa/lsp-python-20170421.322" ((:keywords "python") (:url . "https://github.com/emacs-lsp/lsp-python")) nil] nil deps)
  package-activate(lsp-python)
  package-initialize()
  eval-buffer(#<buffer  *load*> nil "/home/octocat/.emacs.d/init.el" nil t)  ; Reading at buffer position 544
  load-with-code-conversion("/home/octocat/.emacs.d/init.el" "/home/octocat/.emacs.d/init.el" t t)
  load("/home/octocat/.emacs.d/init" t t)
  #[0 "\205\266

**Comment by vibhavp** [comment]
Have you installed lsp-mode too?

**Comment by wiedzmin** [comment]
Yes, my setup is:

(req-package lsp-mode
  :require flycheck
  :config
  (global-lsp-mode))
....
(req-package lsp-python
  :require lsp-mode)

Is it something wrong here?

**Comment by wiedzmin** [comment]
By the way, after manually removing autoload cookie and respective autogenerated code from lsp-python-autoloads.el all works just fine.
