### ISSUE TITLE
Features of plugin from the language server

### ISSUE THREAD

**Issue by innerout** [emacs-lsp/lsp-python#12]
Does the plugin support all the features of the language server or is it a WIP? The only feature i was able to use is the auto completion.

**Comment by valignatev** [comment]
find definition works for me with `xref-fing-definition`, and `xref-find-references` as well.

**Comment by innerout** [comment]
Does auto indentation work?

**Comment by valignatev** [comment]
`lsp-format-buffer` works pretty good for me. I haven't tested it on the complex python files, but so far I don't have any issue.

**Comment by innerout** [comment]
Can you post the relative functions for each feature you know in order to test them?

**Comment by valignatev** [comment]
it's in lsp-mode docs under [examples](https://github.com/emacs-lsp/lsp-mode#examples) section:
* `completion-at-point` for autocompletion
* `xref-find-definitions` for definitions
* `xref-find-references` for references
* `lsp-format-buffer` for formatting.
And there are others, check them in readme section of lsp-mode

**Comment by innerout** [comment]
OK thank you.
