### ISSUE TITLE
Doesn't work in single python file

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-python#28]
I upgraded `lsp-python` to the latest version today. It seems not working now.
I revert to old version as below, it works again. What happened?

```elisp
(lsp-define-stdio-client lsp-python "python"
                         (lsp-make-traverser #'(lambda (dir)
                                                 (if lsp-python-use-init-for-project-root
                                                     (not (directory-files dir nil "__init__.py"))
                                                   (directory-files
                                                    dir
                                                    nil
                                                    "setup.py\\|Pipfile\\|setup.cfg\\|tox.ini"))))
                         nil
                         :command-fn 'lsp-python--ls-command)
```

**Comment by yyoncho** [comment]
Did you try with latest lsp-mode? There was a change in how lsp-mode looks for project root. It no longer resolves the project root by looking for __init__.py but it uses projectile/project.el to find the project root. If you are not in git repo you can create .projectile file in the concreate directory.

**Comment by seagle0128** [comment]
@yyoncho Yes. I am using the latest `lsp-mode`.

I agree with @vibhavp . 
`lsp-mode` uses `projectile` to detects project root. If not detecting, `lsp-mode` uses the current directory before. But the latest commit of `lsp-python` broke this behavior. If I just want to edit a single file temporally, should I create a `.projectile` file for it? What should I do for `Org Src code blocks`?  I think it's a compatibility issue. The current behavior is wired.

**Comment by yyoncho** [comment]
@vibhavp 
> Is this an ideal approach to project detection? 

No, it's not. There are cases which automatic root detection does not work no matter what the logic is. As part of https://github.com/emacs-lsp/lsp-mode/issues/424 I am changing `lsp-mode` to interactively select the project root in case the automatic detection fails. The next time you open that file it will reuse the first selected project root. In this way works VSCode/Theia/Eclipse Che - you interactively select what are the root folders. 

>  What should I do for Org Src code blocks?

create one folder `/home/user/.fake-project-root/` , place .projectile file in it and use it for :file src block parameter.

**Comment by seagle0128** [comment]
@yyoncho 

> create one folder /home/user/.fake-project-root/ , place .projectile file in it and use it for :file src block parameter.

Thanks. This workaround works but need some manual steps but no need before.

**Comment by yyoncho** [comment]
I have it that way, they it was changed by @MaskRay in https://github.com/emacs-lsp/lsp-mode/pull/447/files . @MaskRay, can you share your concerns?

**Comment by seagle0128** [comment]
BTW, I think this could fix it. Thoughts?

```elisp
(defun lsp--suggest-project-root ()
  "Get project root."
  (or
   (when (featurep 'projectile) (projectile-project-root))
   (when (featurep 'project)
     (when-let ((project (project-current)))
       (car (project-roots project))))
   default-directory))
```

**Comment by yyoncho** [comment]
I am fine with this approach.

**Comment by seagle0128** [comment]
OK. I've submitted https://github.com/emacs-lsp/lsp-mode/pull/470. Please review. Thanks.

**Comment by MaskRay** [comment]
I don't like the change. If you do want `default-directory` as a fallback, please set `projectile-require-project-root` to `nil`.
