### ISSUE TITLE
(file-missing "Cannot open load file" "No such file or directory" "lsp-common")

### ISSUE THREAD

**Issue by damon-kwok** [emacs-lsp/lsp-python#32]
(file-missing "Cannot open load file" "No such file or directory" "lsp-common")

**Comment by changephilip** [comment]
In the upstream library,  lsp-mode doesn't have lsp-common now.
[https://github.com/emacs-lsp/lsp-python]

**Comment by yyoncho** [comment]
This package is no longed needed, the python configuration is now part of lsp-clients.el . Please refer to the README. If you have questions ping us on https://gitter.im/emacs-lsp/lsp-mode

**Comment by damon-kwok** [comment]
thanks
